---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: streams-{{cookiecutter.project_slug}}-basic-auth
  namespace: streams
spec:
  basicAuth:
    secret: streams-{{cookiecutter.project_slug}}-basic-auth
